# Markdown linting rules

# Default state for rules
default: true

# Path to files to ignore
ignore:
  - node_modules/
  - .git/

# MD003/heading-style/header-style
MD003:
  style: "atx"

# MD004/ul-style
MD004:
  style: "dash"

# MD013/line-length
MD013: false  # Disable line length limit for documentation

# MD024/no-duplicate-heading
MD024:
  siblings_only: true

# MD029/ol-prefix
MD029:
  style: "ordered"

# MD033/no-inline-html
MD033: false  # Allow inline HTML for advanced formatting

# MD041/first-line-heading
MD041: true  # Require first line to be a heading